# Numpy (Numeric Python):

- It is the primary python package for scientific computing. Most libraries are built upon numpy (sklearn, pandas etc.)
- To manipulate and compute large arrays and matrices of numeric data.
- To compute vector and matrix operations quickly.
- Functionality: A lot built in functionalities (convolutions, fast searching, basic statistics, linear algebra, etc.)
- More efficiently implemented and convenient.
- Speed: Significantly faster than python list.. (Yep!)

In [1]:
import numpy as np 

# 1-D Array

In [2]:
a = np.array([1, 2, 3, 4, 5]) # Arrays are similar to list EXCEPT that every element must be of the same type
print(a)

[1 2 3 4 5]


In [3]:
print(type(a))       # Prints "<class 'numpy.ndarray'>"
print(a.shape)       # Prints (3, )
print(a[0], a[1])    # Prints 1, 2

<class 'numpy.ndarray'>
(5,)
1 2


In [4]:
a[0] = 0        # change the first element of an array
print(a)        # [0, 2, 3, 4, 5]

[0 2 3 4 5]


# Multi-D Arrays

In [5]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(b.shape)  # Prints (2, 4)
print(len(b))   # Prints 2 

(2, 4)
2


# Array Slicing

NumPy allows you to slice arrays with the following syntax form: 
    
arr[a:b, c:d, ..., y:z]

where arr is an n-dimensional array and each pair of the form a:b is the starting and ending index for a specific axis.

In [7]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [8]:
# Things to try out for the inquisitive mind

# Is slicing inclusive? Exclusive? Neither?
# Can you use negative indices?
# What happens if "a" > "b" in a:b? Is this what you expected? If not, is there a way to make it so?
# What happens if you leave "a" out of the a:b pair? What about "b"? What about leaving out both?
# What happens if you append an extra "index" so you have a:b:c? Is this an index? If not, what is it?
# What happens if you leave "a" or "b" (or both) out of the triple a:b:c? 
# How can you get a single row from B?
# How can you get a single column from B?

# Basic Array Operations

## 1-D Array

In [9]:
# 1-D Array
a = np.array([1, 2, 3, 4])
print("Sum:        ",     a.sum())             # Sum 
print("Product:    ",     a.prod())            # Product
print("Mean:       ",     a.mean())            # Mean
print("Variance:   ",     a.var())             # Variance
print("SD :        ",     a.std())             # Standard Diviation

print("Min, index: ",   a.min(), a.argmin()) # Min value, index
print("Max, index: ",   a.max(), a.argmax()) # Max value, index

Sum:         10
Product:     24
Mean:        2.5
Variance:    1.25
SD :         1.118033988749895
Min, index:  1 0
Max, index:  4 3


In [10]:
a = np.array([5, 2, 3, 1, 0, 2, 1])
print("Sorted (ascending ):  ", sorted(a))
print("Sorted (descending ): ", sorted(a, reverse=True))
print("Unique Elements:      ", np.unique(a))

Sorted (ascending ):   [0, 1, 1, 2, 2, 3, 5]
Sorted (descending ):  [5, 3, 2, 2, 1, 1, 0]
Unique Elements:       [0 1 2 3 5]


## Multi-D Array

In [11]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5],    [7, 8]])
print(x + y)                    # Throws error because the dimensions aren't the same
print(np.add(x, y))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x.shape)                  
print(y.shape)

(2, 2)
(2, 2)


In [13]:
print("x + y: \n")
print(x + y)
print(np.add(x, y))

print("\nx - y: \n")
print(x - y)
print(np.subtract(x, y))

print("\nx * y: \n")
print(x * y)
print(np.multiply(x, y))

print("\nx / y: \n")
print(x / y)
print(np.divide(x, y))

print("\nSqrt(x): \n")
print(np.sqrt(x))

x + y: 

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]

x - y: 

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]

x * y: 

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]

x / y: 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Sqrt(x): 

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [14]:
v = np.array([9])
print(v.shape)
print(x.shape)
print(np.dot(x, v))

(1,)
(2, 2)


ValueError: shapes (2,2) and (1,) not aligned: 2 (dim 1) != 1 (dim 0)

In [15]:
v = np.array([9, 10])
print(v.shape)
print(x.shape)
print(np.dot(x, v))

(2,)
(2, 2)
[29 67]


## Boolean comparisons


In [16]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 2, 2, 4])

print("a > b:  ", a > b)
print("a < b:  ", a < b)
print("a == b: ", a == b)
print("a >= b: ", a >= b)
print("a <= b: ", a <= b)

a > b:   [False False False False]
a < b:   [False  True False  True]
a == b:  [ True False  True False]
a >= b:  [ True False  True False]
a <= b:  [ True  True  True  True]
