# Array creation routines

## Ones and zeros

In [2]:
import numpy as np

Create a $2\times2$ array of integers, without initializing entries.

Let $X$ = np.array([1,2,3], [4,5,6], dtype=np.int32). Create a new array with the same shape and type as $X$.

In [14]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
print(X.shape, X.dtype)
X

(2, 3) int32


array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

Create a $3\times2$ array of floats, filled with ones.

Let $X$ = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as $X$.

In [6]:
X = np.arange(4, dtype=np.int64)
X

array([0, 1, 2, 3], dtype=int64)

Create a $3\times2$ array of floats, filled with zeros.

Let $X$ = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as $X$.

In [7]:
X = np.arange(4, dtype=np.int64)
X

array([0, 1, 2, 3], dtype=int64)

Create a $2\times5$ array of uints, filled with sixes.

Let $X$ = np.arange(4, dtype=np.int64). Create an array of sixes with the same shape and type as $X$.

In [8]:
X = np.arange(4, dtype=np.int64)


## From existing data

Create the array [1, 2, 3].

Let $x$ = [1, 2]. Convert it into an array.

In [9]:
x = [1,2]
type(x) # not an array

list

Let $X$ = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [16]:
X = np.array([[1, 2], [3, 4]])
type(X) # not a matrix, technically

numpy.ndarray

Let $x$ = [1, 2]. Convert it into an array of `float`.

In [8]:
x = [1, 2]


Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [9]:
x = np.array([30])


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [10]:
x = np.array([1, 2, 3])


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

## Building matrices

Let $X$ = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of $X$, that is, [0, 5, 10].

In [11]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

Create an array which looks like below.

$\begin{bmatrix} 0 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 0 \\
\end{bmatrix}$

Create an array which looks like below.

$\begin{bmatrix}
0 & 0 & 0 \\
4 & 0 & 0 \\
7 & 8 & 0 \\
10 & 11 & 12 \\
\end{bmatrix}$

Create an array which looks like below.

$\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
0 & 8 & 9 \\
0 & 0 & 12 \\
\end{bmatrix}$