# Array manipulation routines

In [ ]:
import numpy as np

In [ ]:
np.__version__

Q1. Let $X$ be a $10\times 10\times 3$ ndarray with all elements set to one. Reshape $X$ so that the size of the second dimension equals 150.

Q2. Let $X=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}$ be a 2D array. Convert it to a 1D array.

Q3. Let $X=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}$. Get the element 5.

Q4. Let $X$ be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of $X$ such that the new shape will be (4,3,5).


Q5. Let $X$ be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of $X$ such that the new shape will be (4,3).

Q5. Let $X$ be an arbitrary 2-D array of shape (3, 4). Insert a new axis such that the new shape will be (3, 1, 4).

Q6. Let $X$ be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

Q7. Let $X=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix}$
and 
$Y=\begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}$

Concatenate $X$ and $Y$ so that a new array
$Z=\begin{bmatrix}
1 & 2 & 3 & 7 & 8 & 9 \\
4 & 5 & 6 & 10 & 11 & 12
\end{bmatrix}$

Q8. Let $X=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix}$
and 
$Y=\begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}$

Concatenate $X$ and $Y$ so that the new array
$Z=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}$

Q9. Let $X=\begin{bmatrix} 1 & 2 & 3\end{bmatrix}$ and $Y=\begin{bmatrix} 4 & 5 & 6\end{bmatrix}$. Convert it to $Z=\begin{bmatrix} 
1 & 4 \\ 
2 & 5 \\
3 & 6
\end{bmatrix}$.

Q10. Let $X=\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}$ and $Y=\begin{bmatrix}
4 \\
5 \\
6 
\end{bmatrix}$. Create the array $Z=\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 
\end{bmatrix}$ by concatenating $X$ and $Y$.

Q11. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

Q12. 
Let $X=\begin{bmatrix}
\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7
\end{bmatrix} & \begin{bmatrix}
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15 \\
\end{bmatrix} \end{bmatrix}$.

Split it so that we have $Y=\begin{bmatrix}
\begin{bmatrix}
0 & 1 & 2 \\
4 & 5 & 6
\end{bmatrix} & \begin{bmatrix}
8 & 9 & 10 \\
12 & 13 & 14
\end{bmatrix} \end{bmatrix}$ and $Z=\begin{bmatrix}
\begin{bmatrix}
3 \\
7
\end{bmatrix} & \begin{bmatrix}
11 \\
15 \\
\end{bmatrix} \end{bmatrix}$.

Q13. Let $X=\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15
\end{bmatrix}$.

Split it into two arrays along the second axis.

Q14. Let $X=\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15
\end{bmatrix}$.
Split it into two arrays along the first axis.

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
$\begin{bmatrix}
0 & 1 & 2 & 0 & 1 & 2 \\
0 & 1 & 2 & 0 & 1 & 2
\end{bmatrix}$

Q16. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

Q17. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

Q18. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


Q19. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

Q20. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

Q21. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

Q22. Let x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.